<?php
$nombre= $_POST ['nombre'];
$correo= $_POST ['correo'];
$pass=$_POST ['pwd'];
$persona=$_POST ['persona'];
$pais=$_POST ['pais'];
$labiales=$_POST ['labiales'];
$color=$_POST ['color'];
$polvos=$_POST ['polvos'];
$color2=$_POST ['color2'];
$rubor=$_POST ['rubor'];
$color3=$_POST ['color3'];
$sombras=$_POST ['sombras'];
$color4=$_POST ['color4'];
$iluminador=$_POST ['iluminador'];
$color5=$_POST ['color5'];
$crema=$_POST ['crema'];
$color6=$_POST ['color6'];
$mascara=$_POST ['mascara'];
$color7=$_POST ['color7'];
$corrector=$_POST ['corrector'];
$color8=$_POST ['color8'];

echo "<h2>LA INFORMACION DE SU PEDIDO ES:</h2>";
echo "El nombre recibido es:". $nombre. "<br/>";
echo "El correo es:". $correo. "<br/>";
echo "la contraseña es: <br/>";
echo "la persona es:". $persona. "<br/>";
echo "El pais  es:". $pais. "<br/>";
echo "El pedido de labiales son :". $labiales. "<br/>";
echo "El color del labial es :". $color. "<br/>";
echo "El pedido de polvos son :". $polvos. "<br/>";
echo "El color del polvo es:". $color2. "<br/>";
echo "El pedido de rubor es:". $rubor. "<br/>";
echo "El color del rubor es:". $color3. "<br/>";
echo "El pedido de sombras  es:". $sombras. "<br/>";
echo "El color del sombras es:". $color4. "<br/>";
echo "El pedido de iluminador :". $iluminador. "<br/>";
echo "El color de iluminador es:". $color5. "<br/>";
echo "El pedido de la crema hidratante  es:". $crema. "<br/>";
echo "El color de la crema hidratante es:". $color6. "<br/>";
echo "El pedido de mascara es:". $mascara. "<br/>";
echo "El color de las mascara  es:". $color7. "<br/>";
echo "El pedido del correptor es:". $corrector. "<br/>";
echo "El color del correptor es:". $color8. "<br/>";
?>